Repository bitbrain/beehave, pull requests merged in 2022-12, with the labels that each got.

#62 added static typing
  addons/beehave/nodes/beehave_node.gd
  addons/beehave/nodes/beehave_root.gd
  addons/beehave/nodes/beehave_tree.gd
  addons/beehave/nodes/composites/selector.gd
  addons/beehave/nodes/composites/selector_star.gd
  addons/beehave/nodes/composites/sequence.gd
  addons/beehave/nodes/composites/sequence_star.gd
  addons/beehave/nodes/decorators/failer.gd
  addons/beehave/nodes/decorators/inverter.gd
  addons/beehave/nodes/decorators/limiter.gd
  addons/beehave/nodes/decorators/succeeder.gd
Labels: 🌺 enhancement

#66 Added interrupt method for long running actions
  addons/beehave/nodes/beehave_node.gd
  addons/beehave/nodes/beehave_root.gd
  addons/beehave/nodes/composites/composite.gd
  addons/beehave/nodes/composites/selector.gd
  addons/beehave/nodes/composites/selector_star.gd
  addons/beehave/nodes/composites/sequence.gd
  addons/beehave/nodes/composites/sequence_star.gd
Labels: 🍯 feature, 🍒 cherrypick:godot3, 🟡 changes requested

#80 Show editor warnings on wrong configuration
  addons/beehave/nodes/beehave_node.gd
  addons/beehave/nodes/beehave_root.gd
  addons/beehave/nodes/beehave_tree.gd
  addons/beehave/nodes/composites/composite.gd
  addons/beehave/nodes/composites/selector.gd
  addons/beehave/nodes/composites/selector_star.gd
  addons/beehave/nodes/composites/sequence.gd
  addons/beehave/nodes/composites/sequence_star.gd
  addons/beehave/nodes/decorators/decorator.gd
  addons/beehave/nodes/decorators/failer.gd
  addons/beehave/nodes/decorators/inverter.gd
  addons/beehave/nodes/decorators/limiter.gd
  addons/beehave/nodes/decorators/succeeder.gd
  addons/beehave/nodes/leaves/action.gd
  addons/beehave/nodes/leaves/condition.gd
  addons/beehave/nodes/leaves/leaf.gd
  tests/BeehaveTestScene.tscn
Labels: 🍯 feature

#90 New nodes: SequenceRandom and SelectorRandom
  README.md
  addons/beehave/icons/selector_random.svg
  addons/beehave/icons/sequence_random.svg
  addons/beehave/nodes/composites/selector_random.gd
  addons/beehave/nodes/composites/sequence_random.gd
Labels: 🍯 feature, 🟡 changes requested, 🐝 new node
