Repository bitbrain/beehave, pull requests merged in 2023-01, with the labels that each got.

#98 :recycle: merge BeehaveRoot into BeehaveTree
  addons/beehave/nodes/beehave_node.gd
  addons/beehave/nodes/beehave_root.gd
  addons/beehave/nodes/beehave_tree.gd
  examples/actions/SetModulateColor.gd
  examples/actions/SetModulateColor.tscn
  examples/conditions/HasNegativePosition.gd
  examples/conditions/HasNegativePosition.tscn
  examples/conditions/HasPositivePosition.gd
  examples/conditions/HasPositivePosition.tscn
  project.godot
  tests/BeehaveTestScene.gd
  tests/BeehaveTestScene.tscn
Labels: 🌺 enhancement, 💥 breaks compatibility

#102 :zap: improve performance of get_running_action
  addons/beehave/nodes/beehave_tree.gd
  addons/beehave/nodes/composites/selector.gd
  addons/beehave/nodes/composites/selector_random.gd
  addons/beehave/nodes/composites/selector_star.gd
  addons/beehave/nodes/composites/sequence.gd
  addons/beehave/nodes/composites/sequence_random.gd
  addons/beehave/nodes/composites/sequence_star.gd
  addons/beehave/nodes/decorators/failer.gd
  addons/beehave/nodes/decorators/inverter.gd
  addons/beehave/nodes/decorators/limiter.gd
  addons/beehave/nodes/decorators/succeeder.gd
  examples/actions/SetModulateColor.gd
  tests/BeehaveTestScene.gd
  tests/BeehaveTestScene.tscn
Labels: 🌺 enhancement

#103 Implement performance metrics BehaveTree Node
  addons/beehave/nodes/beehave_tree.gd
Labels: 🍯 feature

#106 :bug: address memory leak for blackboards
  addons/beehave/nodes/beehave_tree.gd
Labels: 🐛 bug

#107 :bug: set correctly last condition on decorators
  addons/beehave/nodes/decorators/failer.gd
  addons/beehave/nodes/decorators/inverter.gd
  addons/beehave/nodes/decorators/limiter.gd
  addons/beehave/nodes/decorators/succeeder.gd
Labels: 🐛 bug
