Repository bitbrain/beehave, pull requests merged in 2023-02, with the labels that each got.

#121 Fix: Check child count before applying interrupt
  addons/beehave/nodes/beehave_tree.gd
  test/UnitTestScene.tscn
Labels: 🐛 bug

#126 Added `enter()` and `exit()` methods for beehave nodes
  README.md
  addons/beehave/nodes/beehave_node.gd
  addons/beehave/nodes/beehave_tree.gd
  addons/beehave/nodes/composites/selector.gd
  addons/beehave/nodes/composites/selector_random.gd
  addons/beehave/nodes/composites/selector_star.gd
  addons/beehave/nodes/composites/sequence.gd
  addons/beehave/nodes/composites/sequence_random.gd
  addons/beehave/nodes/composites/sequence_star.gd
  addons/beehave/nodes/decorators/decorator.gd
  addons/beehave/nodes/decorators/failer.gd
  addons/beehave/nodes/decorators/inverter.gd
  addons/beehave/nodes/decorators/limiter.gd
  addons/beehave/nodes/decorators/succeeder.gd
  test/actions/count_up_action.gd
  test/actions/mock_action.gd
  test/before_after_run_test.gd
  test/nodes/composites/selector_star_test.gd
  test/nodes/composites/sequence_random_test.gd
  test/nodes/composites/sequence_star_test.gd
  test/nodes/composites/sequence_test.gd
  test/nodes/decorators/failer_test.gd
  test/nodes/decorators/inverter_test.gd
  test/nodes/decorators/limiter_test.gd
  test/nodes/decorators/succeeder_test.gd
Labels: 🍯 feature

#133 🐞 Implemented debug view
  addons/beehave/debug/debugger.gd
  addons/beehave/debug/debugger_tab.gd
  addons/beehave/debug/frames.gd
  addons/beehave/debug/graph_edit.gd
  addons/beehave/debug/graph_node.gd
  addons/beehave/debug/tree_node.gd
  addons/beehave/icons/port_bottom.svg
  addons/beehave/icons/port_top.svg
  addons/beehave/nodes/beehave_node.gd
  addons/beehave/nodes/beehave_tree.gd
  addons/beehave/nodes/composites/composite.gd
  addons/beehave/nodes/composites/selector.gd
  addons/beehave/nodes/composites/selector_random.gd
  addons/beehave/nodes/composites/selector_star.gd
  addons/beehave/nodes/composites/sequence.gd
  addons/beehave/nodes/composites/sequence_random.gd
  addons/beehave/nodes/composites/sequence_star.gd
  addons/beehave/nodes/decorators/decorator.gd
  addons/beehave/nodes/decorators/failer.gd
  addons/beehave/nodes/decorators/inverter.gd
  addons/beehave/nodes/decorators/limiter.gd
  addons/beehave/nodes/decorators/succeeder.gd
  addons/beehave/nodes/leaves/action.gd
  addons/beehave/nodes/leaves/condition.gd
  addons/beehave/nodes/leaves/leaf.gd
  addons/beehave/plugin.gd
  addons/beehave/utils/utils.gd
Labels: 🍯 feature

#112 🚧 Gdunit GitHub action (WIP)
  .github/actions/godot-install/action.yml
  .github/actions/publish-test-report/action.yml
  .github/actions/unit-test/action.yml
  .github/actions/upload-test-report/action.yml
  .github/workflows/beehave-ci.yml
  addons/gdUnit4/bin/GdUnitCmdTool.gd
  addons/gdUnit4/bin/ProjectScanner.gd
  addons/gdUnit4/src/GdUnitAwaiter.gd
  addons/gdUnit4/src/GdUnitSceneRunner.gd
  addons/gdUnit4/src/GdUnitTestSuite.gd
  addons/gdUnit4/src/asserts/GdAssertMessages.gd
  addons/gdUnit4/src/cmd/CmdConsole.gd
  addons/gdUnit4/src/core/GdObjects.gd
  addons/gdUnit4/src/core/GdUnitClassDoubler.gd
  addons/gdUnit4/src/core/GdUnitExecutor.gd
  addons/gdUnit4/src/core/GdUnitMemoryPool.gd
  addons/gdUnit4/src/core/GdUnitRunner.gd
  addons/gdUnit4/src/core/GdUnitRunnerConfig.gd
  addons/gdUnit4/src/core/GdUnitSceneRunnerImpl.gd
  addons/gdUnit4/src/core/GdUnitSignals.gd
  addons/gdUnit4/src/core/GdUnitSingleton.gd
  addons/gdUnit4/src/core/GdUnitTestSuiteScanner.gd
  addons/gdUnit4/src/core/GdUnitTools.gd
  addons/gdUnit4/src/core/_TestCase.gd
  addons/gdUnit4/src/core/parse/GdDefaultValueDecoder.gd
  addons/gdUnit4/src/core/report/GdUnitReport.gd
  addons/gdUnit4/src/core/report/GdUnitReportCollector.gd
  addons/gdUnit4/src/core/scan_project.gd
  addons/gdUnit4/src/report/GdUnitByPathReport.gd
  addons/gdUnit4/src/report/GdUnitHtmlPatterns.gd
  addons/gdUnit4/src/report/GdUnitHtmlReport.gd
  addons/gdUnit4/src/report/GdUnitReportSummary.gd
  addons/gdUnit4/src/report/GdUnitTestCaseReport.gd
  addons/gdUnit4/src/report/GdUnitTestSuiteReport.gd
  addons/gdUnit4/src/report/JUnitXmlReport.gd
  addons/gdUnit4/src/report/XmlElement.gd
  addons/gdUnit4/src/spy/GdUnitSpyBuilder.gd
  runtest.cmd
  runtest.sh
  test/blackboard_test.gd
Labels: ⚙ workflow

#147 fix: tree node positioning logic
  addons/beehave/debug/tree_node.gd
Labels: 🐛 bug

#159 add images to docs
  README.md
  assets/logo.svg
  assets/logo.svg.import
  docs/README.md
  docs/assets/beehave-demo-tree.png
  docs/assets/debug-tree.gif
  docs/assets/example.png
  docs/assets/gdunit-testrun.gif
  docs/assets/logo 2.svg
  docs/assets/performance-monitor.gif
Labels: 📙 docs

#161 interrupt running task if other task starts running
  addons/beehave/nodes/composites/selector.gd
  addons/beehave/nodes/composites/sequence.gd
  test/nodes/composites/selector_test.gd
  test/nodes/composites/sequence_test.gd
Labels: 🐛 bug, 🟡 changes requested
